import Link from "next/link";
import type {ArchiveProject} from "@/data/projects";
import {PageHeading} from "./page-heading";
import {FridayCaseStudy} from "./friday-case-study";
import {projectNotes} from "@/data/project-notes";
export function CaseStudy({project:p,nextProject}:{project:ArchiveProject;nextProject:ArchiveProject}){
if(p.slug==='friday')return <FridayCaseStudy project={p} nextProject={nextProject}/>;
const chapters=[{label:'The problem',body:p.problem},{label:'Why this exists',body:p.why??p.context},{label:'The system',body:p.implemented},{label:'Engineering',body:p.engineering},{label:'Key decisions',body:p.decisions},{label:'Challenges & limits',body:p.limitations},{label:'What can be inspected',body:p.result},{label:'Learning',body:p.learning}];
return <><div className="case-back wrap"><Link className="text-link" href="/projects">← All projects</Link><span className="eyebrow">{p.status??'Documentation in progress'}</span></div><PageHeading season="Autumn" era="Project record" title={p.name}><p>{p.description}</p></PageHeading>
{p.media?.map(m=><figure className="case-media wrap" key={m.source}><img src={m.source} alt={m.alt} width="1200" height="750"/><figcaption>{m.caption}</figcaption></figure>)}
<div className="case-layout wrap"><aside className="case-index"><p className="eyebrow">Inside this project</p><nav aria-label="Case study chapters">{chapters.map((c,i)=><a key={c.label} href={`#chapter-${i}`}>{String(i+1).padStart(2,'0')} {c.label}</a>)}</nav>{p.tools&&<><h2>Working with</h2><p>{p.tools.join(' · ')}</p></>}{p.role&&<><h2>My role</h2><p>{p.role}</p></>}{p.links?.map(l=><a key={l.href} className="text-link" href={l.href} target="_blank" rel="noreferrer">{l.label} ↗</a>)}</aside>
<div className="case-chapters">{chapters.map((c,i)=><section id={`chapter-${i}`} key={c.label}><span className="eyebrow">0{i+1}</span><h2>{c.label}</h2>{Array.isArray(c.body)?<ul>{c.body.map(b=><li key={b}>{b}</li>)}</ul>:<p className={!c.body?'muted':''}>{c.body??(c.label==='Learning'?'Personal retrospective not yet recorded.':'This part of the project record is not yet documented.')}</p>}{i===3&&projectNotes[p.slug]?.map(note=><details className="engineering-note" key={note.title}><summary>{note.title}</summary><p>{note.body}</p>{note.source&&<a className="text-link" href={note.source} target="_blank" rel="noreferrer">Inspect the source ↗</a>}</details>)}</section>)}<aside className="source-note"><h2>Keep the source with the story.</h2><p>{p.sourceNote??'This project is preserved from the earlier portfolio. Detailed implementation evidence has not yet been recovered.'}</p>{p.links?.filter(l=>l.type==='source').map(l=><a className="text-link" key={l.href} href={l.href} target="_blank" rel="noreferrer">Read the source documentation ↗</a>)}</aside></div></div><div className="chapter wrap"><p className="eyebrow">Next project</p><Link className="next-project" href={`/projects/${nextProject.slug}`}>{nextProject.name} <span aria-hidden="true">↗</span></Link></div></>;
}
