"use client";
import {useState} from "react";
import type {PortfolioCreative,ContentSource} from "@/lib/portfolio-api";
export function CreativeSignals({creative,source,signalsSource}:{creative:PortfolioCreative;source:ContentSource;signalsSource:ContentSource}){
const [player,setPlayer]=useState(false);
return <section className="creative-signals chapter wrap" id="creative-signals" data-content-source={source} data-signals-source={signalsSource}><div className="section-top"><div><p className="eyebrow">Creative signals</p><h2>A different kind<br/>of world-building.</h2></div><p>Stories, images and sound. The same curiosity, speaking in other forms.</p></div>
<article className="story-chapter" id="manhwa"><a className="story-cover" href={creative.webtoon.href} target="_blank" rel="noreferrer"><img src={creative.webtoon.cover} alt="ERROR 404: HERO NOT FOUND original cover, credited to Bhuvan Gowda P" width="1200" height="1200" loading="lazy"/></a><div><p className="eyebrow">WEBTOON CANVAS / {creative.webtoon.genre}</p><h3>{creative.webtoon.title}</h3><p>{creative.webtoon.description}</p><p className="story-credit">Created by Bhuvan Gowda P</p><a className="button primary" href={creative.webtoon.href} target="_blank" rel="noreferrer">Read on WEBTOON ↗</a></div></article>
<article className="music-chapter" id="music"><div className="record-art" aria-hidden="true"><div className="record-disc"><div><span>BGP</span><small>CREATIVE SIGNALS</small></div></div><span className="record-caption">SOUND / ANOTHER BRANCH</span></div><div className="music-copy"><p className="eyebrow">Music / Spotify</p><h3>Some ideas<br/>need a rhythm.</h3><p>{creative.music.description}</p><p className="artist-name">{creative.music.artist}</p><div className="music-themes" aria-label="Music in the creative practice"><span>Rhythm</span><span>Atmosphere</span><span>Emotion</span></div><div className="actions"><a className="text-link" href={creative.music.href} target="_blank" rel="noreferrer">Explore my music on Spotify ↗</a><button className="button" type="button" aria-expanded={player} aria-controls="spotify-player" onClick={()=>setPlayer(p=>!p)}>{player?'Close player':'Load Spotify player'}</button></div><p className="media-caption">Browse the current catalogue in the official artist player. It connects to Spotify only when you load it; playback starts with you.</p></div><div id="spotify-player" className="spotify-container">{player&&<iframe title="Bhuvan’s official Spotify artist player" src={creative.music.embed} width="100%" height="352" allow="encrypted-media; fullscreen; picture-in-picture" loading="lazy"/>}</div></article></section>;
}
