import {expect,test,type Page} from "@playwright/test";
async function seek(page:Page,t:number){await page.evaluate(t=>{const e=document.querySelector<HTMLElement>('.intro-sequence')!,s=e.querySelector<HTMLElement>('.sequence-stage')!;window.scrollTo({top:e.offsetTop-80+(e.offsetHeight-s.offsetHeight)*t,behavior:'instant'});},t);}
for(const mobile of [false,true])test(`sequence follows slow, fast and reverse scroll on ${mobile?'mobile':'desktop'}`,async({page})=>{
 await page.setViewportSize(mobile?{width:390,height:844}:{width:1440,height:900});await page.goto('/');const intro=page.getByTestId('intro-sequence');await expect(intro).toHaveAttribute('data-mode','active');
 for(const t of [0,.02,.04,.08,.5,.98,.6,.58,.56,.01,.8,.2,1,0]){await seek(page,t);await expect.poll(async()=>Number(await intro.getAttribute('data-frame-index'))).toBeCloseTo(Math.round(t*159),0);await expect.poll(async()=>Number(await intro.getAttribute('data-rendered-frame')),{timeout:10000}).toBeCloseTo(Math.round(t*159),0);await expect(page.locator('canvas')).toHaveCSS('opacity','1');expect(Number(await intro.getAttribute('data-cache-size'))).toBeLessThanOrEqual(mobile?24:36);}
 await page.getByRole('button',{name:'Skip intro',exact:true}).click();await expect(page.locator('#selected-work')).toBeFocused();await page.getByRole('button',{name:/Replay intro/}).click();await expect(intro).toHaveAttribute('data-frame-index','0');
});
test('range control provides a keyboard alternative',async({page})=>{await page.goto('/');await page.getByText('Portrait controls',{exact:true}).click();const range=page.getByRole('slider',{name:'Choose a frame'});await expect(range).toBeVisible();await range.focus();await page.keyboard.press('End');await expect(page.getByTestId('intro-sequence')).toHaveAttribute('data-frame-index','159');});

test('slow asynchronous decoding does not freeze forward or reverse input',async({page})=>{
 await page.setViewportSize({width:1440,height:900});
 await page.addInitScript(()=>{const original=window.createImageBitmap.bind(window);window.createImageBitmap=async(...args:unknown[]):Promise<ImageBitmap>=>{const bitmap:ImageBitmap=await Reflect.apply(original,window,args);await new Promise(resolve=>setTimeout(resolve,115));return bitmap;};});
 await page.goto('/');const intro=page.getByTestId('intro-sequence');await expect(intro).toHaveAttribute('data-mode','active');
 for(const t of [.1,.8,.2,.9,.02]){await seek(page,t);await expect.poll(async()=>Number(await intro.getAttribute('data-rendered-frame')),{timeout:10000}).toBe(Math.round(t*159));await expect(intro).toHaveAttribute('data-mode','active');}
 // Reverse several times before in-flight cancellation settles, then stop sending events.
 for(const t of [.85,.03,.8,.03,.2]){await seek(page,t);await page.waitForTimeout(25);}
 await expect.poll(async()=>Number(await intro.getAttribute('data-rendered-frame')),{timeout:10000}).toBe(32);
 await expect(intro).toHaveAttribute('data-mode','active');
});
for(const reason of ['reduced-motion','save-data','low-memory'])test(reason+' preserves content without downloading sequence frames',async({browser,baseURL})=>{const ctx=await browser.newContext({baseURL,reducedMotion:reason==='reduced-motion'?'reduce':'no-preference'});if(reason!=='reduced-motion')await ctx.addInitScript(r=>{if(r==='save-data')Object.defineProperty(navigator,'connection',{value:{saveData:true},configurable:true});else Object.defineProperty(navigator,'deviceMemory',{value:1,configurable:true});},reason);const page=await ctx.newPage();const frames:string[]=[];page.on('request',r=>{if(r.url().includes('hero-delivery'))frames.push(r.url());});await page.goto('/');await expect(page.getByTestId('intro-sequence')).toHaveAttribute('data-mode','static');await page.locator('.intro-poster').scrollIntoViewIfNeeded();await expect(page.locator('.intro-poster')).toBeVisible();await expect(page.locator('h1')).toContainText('Curiosity');expect(new Set(frames).size).toBeLessThanOrEqual(1);await ctx.close();});
test('frame failures retain the poster and native scrolling',async({page})=>{await page.route('**/hero-delivery/**',route=>route.request().resourceType()==='fetch'?route.abort():route.continue());await page.goto('/');await seek(page,.2);await expect(page.getByTestId('intro-sequence')).toHaveAttribute('data-mode','paused');await expect(page.locator('.intro-poster')).toBeVisible();await page.getByRole('button',{name:'Skip intro',exact:true}).click();await expect(page.locator('#selected-work')).toBeFocused();});
