import Link from "next/link";
import "./technical-capabilities.css";
import {CreativeSignals} from "@/components/chrono/creative-signals";
import {LaserPortrait} from "@/components/chrono/laser-portrait";
import {CapabilityDetails} from "@/components/profile/capability-details";
import {ContactForm} from "@/components/profile/contact-form";
import {portfolioHistory} from "@/data/achievements";
import {routeMetadata} from "@/lib/metadata";
import {getPortfolioCapabilities,getPortfolioCreative,getPortfolioProfile,getSignalsSource} from "@/lib/portfolio-api";
export const metadata=routeMetadata.about;
export default async function Profile(){const [profileResult,capabilitiesResult,creativeResult,signalsSource]=await Promise.all([getPortfolioProfile(),getPortfolioCapabilities(),getPortfolioCreative(),getSignalsSource()]);const profile=profileResult.data,creatorCapabilities=capabilitiesResult.data;return <><header className="profile-cover wrap"><p className="eyebrow">Equinox / Chrono nexus</p><h1>Many branches.<br/>One Bhuvan.</h1><p className="profile-cover-deck">Builder. Business student. Storyteller. Music creator. The interesting things happen where those worlds meet.</p><div className="actions"><Link className="text-link" href="#manhwa">My WEBTOON ↗</Link><Link className="text-link" href="#music">My music ↗</Link></div><a className="cover-scroll" href="#identity"><span>Meet the person behind the projects</span><span aria-hidden="true">↓</span></a></header>
<section className="profile-intro wrap" id="identity" data-content-source={profileResult.source}><LaserPortrait/><div><p className="eyebrow">Bhuvan Gowda P / Bengaluru, India</p><h2>I build whatever<br/>makes me curious.</h2><p>{profile.introduction}</p><p>Business helps me ask who an idea is for. Technology gives me a way to build it. Editing, stories and music help me decide how it should feel.</p><dl className="profile-facts"><div><dt>Studying</dt><dd>{profile.education.program} · {profile.education.institution}</dd></div><div><dt>Method</dt><dd>Question → Prototype → Observe → Rebuild</dd></div></dl></div></section>
<section className="chapter wrap capabilities" id="capabilities" data-content-source={capabilitiesResult.source}><div className="section-top"><div><p className="eyebrow">How the branches connect</p><h2>A working set,<br/>always growing.</h2></div><p>Things I practise, things I build with, and directions I’m still exploring.</p></div>{creatorCapabilities.map(c=><details key={c.id} id={`capability-${c.id}`}><summary><span>{c.name}</span><small>{c.stage}</small><b aria-hidden="true">+</b></summary><CapabilityDetails capability={c}/></details>)}</section>
<CreativeSignals creative={creativeResult.data} source={creativeResult.source} signalsSource={signalsSource}/>
<section className="chapter wrap"><p className="eyebrow">Version history</p><h2>The roots of this archive.</h2><ol className="history">{portfolioHistory.map(h=><li key={h.version}><span>{h.version}</span><div><h3>{h.title}</h3><p>{h.detail}</p></div></li>)}</ol></section>
<section className="chapter wrap contact-chapter" id="contact"><div className="contact-chapter-copy"><p className="eyebrow">Keep the conversation growing.</p><h2>Have a question?<br/>An idea? A good song?</h2><p>Start with a note. I’m interested in the place where useful technology and creative thinking meet.</p><div className="actions">{profile.contact.email&&<a className="text-link" href={`mailto:${profile.contact.email}`}>Use email instead ↗</a>}{profile.contact.github&&<a className="text-link" href={profile.contact.github} target="_blank" rel="noreferrer">GitHub profile ↗</a>}<a className="text-link" href="https://www.instagram.com/bhuvan5821na/" target="_blank" rel="noreferrer">Instagram ↗</a></div></div><ContactForm fallbackEmail={profile.contact.email}/></section></>;}
