import sequence from "@/data/hero-sequence.json";

/** Generated by scripts/inspect_frames.py from the supplied source directory. */
export const heroFrames = Array.from({ length: sequence.end - sequence.start + 1 }, (_, index) => index + sequence.start)
  .filter((number) => !sequence.missing.includes(number))
  .map((number) => `${sequence.prefix}${String(number).padStart(sequence.padding, "0")}${sequence.extension}`);

export const HERO_FALLBACK = heroFrames[heroFrames.length - 1];

/** Delivery derivatives retain every canonical frame in its original order. */
export const compactHeroFrames = heroFrames.map((src) => src.replace("hero-sequence/", "hero-delivery/compact/").replace(".jpg", ".webp"));
export const largeHeroFrames = heroFrames.map((src) => src.replace("hero-sequence/", "hero-delivery/large/").replace(".jpg", ".webp"));
